name: sand_piles
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.3

dependencies:
  willshex:
    path: ../willshex-dart

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
